<?xml version="1.0" encoding="utf-8"?><Database Name="IP-AdressenDB" Class="DDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HES-EDV-10;Initial Catalog=IP-AdressenDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="IP_AdressenDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Rechte" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Distrikt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Bereiche_User" Member="Bereiche" ThisKey="Distrikt" OtherKey="Id" Type="Bereiche" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bereiche" Member="Bereiche">
    <Type Name="Bereiche">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IP_Bereich3" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="IP_Bereich2" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="IP_Bereich1" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DHCP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Netzmaske" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Bereiche_User" Member="User" ThisKey="Id" OtherKey="Distrikt" Type="User" />
      <Association Name="Bereiche_Geräte" Member="Geräte" ThisKey="Id" OtherKey="Id_Bereich" Type="Geräte" />
    </Type>
  </Table>
  <Table Name="dbo.Geräte" Member="Geräte">
    <Type Name="Geräte">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Art" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Typ" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Standort" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AlteIP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VNC_Port" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VNC_Passwort" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Kommentar" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Id_Bereich" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Port" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Geräte_Adressen" Member="Adressen" ThisKey="Id" OtherKey="Id_Geräte" Type="Adressen" />
      <Association Name="Bereiche_Geräte" Member="Bereiche" ThisKey="Id_Bereich" OtherKey="Id" Type="Bereiche" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Adressen" Member="Adressen">
    <Type Name="Adressen">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAC" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Id_Geräte" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Adb1" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Adb2" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Adb3" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Adb4" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Adb5" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Geräte_Adressen" Member="Geräte" ThisKey="Id_Geräte" OtherKey="Id" Type="Geräte" IsForeignKey="true" />
    </Type>
  </Table>
</Database>